//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dept
    {
        public int Id { get; set; }
        public Nullable<int> InhabitantId { get; set; }
        public Nullable<decimal> WaterAmount { get; set; }
        public Nullable<decimal> ElectricityAmount { get; set; }
    
        public virtual Inhabitant Inhabitant { get; set; }
    }
}
