//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentBill
    {
        public int Id { get; set; }
        public Nullable<int> InhabitantId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public string Period { get; set; }
        public Nullable<decimal> AmountDept { get; set; }
        public Nullable<decimal> AmountPayed { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Inhabitant Inhabitant { get; set; }
    }
}
