//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.RequestExecution = new HashSet<RequestExecution>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string RequestText { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> InhabitantId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Inhabitant Inhabitant { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestExecution> RequestExecution { get; set; }
    }
}
